### ISSUE TITLE
User Controller - Obtener usuario

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-backend#30]
Buenos díass, del lado de backend no se deben retornar información sensible (clave o contraseña), lo ideal es retornar el token con información básica del usuario (Nombre, correo, Rol).

https://github.com/priscilabgmoya/proyecto-final-menu-backend/blob/930ec78363de94316fe7f40a4ea9b0357d86b857/src/controller/usuariosController.js#L186-L197

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-backend/commit/4e30ba694c96599894f4dce702cba8dd243454f6

**Comment by castromaciel** [comment]
Se valida la solución.
